Repository automerge/automerge, pull requests merged in 2021-07, with the labels that each got.

#198 Add cards example.
  automerge/Cargo.toml
  automerge/examples/cards.rs
  automerge/src/lib.rs
Labels: documentation

#207 Check heads when decoding a document
  automerge-backend/src/change.rs
  automerge-backend/src/decoding.rs
Labels: bug

#209 load: Don't generate a patch that will just be dropped
  automerge-backend/src/backend.rs
Labels: performance

#208 load: Reduce intermediate collects and use iterators more
  automerge-backend/src/change.rs
  automerge-backend/src/columnar.rs
Labels: performance

#203 Fix logic for updating changed_indices in diffable sequence
  automerge-frontend/src/state_tree/diffable_sequence.rs
  automerge-protocol/src/lib.rs
Labels: bug

#213 Add is_* and extraction methods to Value and Primitive
  automerge-frontend/src/value.rs
  automerge-frontend/src/value/conflicts.rs
  automerge-frontend/src/value/cursor.rs
  automerge-frontend/src/value/primitive.rs
Labels: documentation, enhancement

#179 Use tinyvec for actor id
  automerge-backend/src/expanded_op.rs
  automerge-frontend/src/lib.rs
  automerge-frontend/tests/test_apply_patch.rs
  automerge-protocol/Cargo.toml
  automerge-protocol/src/lib.rs
  automerge-protocol/src/utility_impls/actor_id.rs
  automerge-protocol/tests/serde_round_trip.rs
  automerge-protocol/tests/serde_round_trip_proptest.rs
  automerge/tests/frontend_backend_roundtrip.rs
  automerge/tests/save_load.rs
Labels: performance

#212 Value proxy
  automerge-frontend/src/lib.rs
  automerge-frontend/src/state_tree/diffable_sequence.rs
  automerge-frontend/src/state_tree/mod.rs
  automerge-frontend/src/state_tree/multivalue.rs
  automerge-frontend/src/value_ref.rs
  automerge-frontend/src/value_ref/list.rs
  automerge-frontend/src/value_ref/map.rs
  automerge-frontend/src/value_ref/root.rs
  automerge-frontend/src/value_ref/table.rs
  automerge-frontend/src/value_ref/text.rs
  automerge/src/lib.rs
Labels: enhancement

#227 Optimistic state tree
  automerge-frontend/src/lib.rs
  automerge-frontend/src/mutation.rs
  automerge-frontend/src/state_tree/mod.rs
  automerge-frontend/src/state_tree/optimistic.rs
Labels: enhancement, performance
