Repository automerge/automerge, pull requests merged in 2021-05, with the labels that each got.

#124 Add derive Arbitrary support behind cargo feature
  automerge-frontend/Cargo.toml
  automerge-frontend/src/value.rs
  automerge-protocol/Cargo.toml
  automerge-protocol/src/lib.rs
Labels: enhancement

#129 Move decoding to a new module and separate errors
  automerge-backend/src/backend.rs
  automerge-backend/src/change.rs
  automerge-backend/src/columnar.rs
  automerge-backend/src/decoding.rs
  automerge-backend/src/encoding.rs
  automerge-backend/src/error.rs
  automerge-backend/src/lib.rs
  automerge-backend/src/sync.rs
  automerge-backend/src/sync/bloom.rs
  automerge-backend/src/sync/state.rs
  automerge-backend/tests/apply_change.rs
Labels: enhancement

#126 Improve filter_changes for sync
  automerge-backend/src/backend.rs
Labels: performance

#130 Change init to new and add defaults
  automerge-backend-wasm/src/lib.rs
  automerge-backend/src/actor_map.rs
  automerge-backend/src/backend.rs
  automerge-backend/src/change.rs
  automerge-backend/src/lib.rs
  automerge-backend/src/op_set.rs
  automerge-backend/tests/apply_change.rs
  automerge-backend/tests/apply_local_change.rs
  automerge-backend/tests/get_changes.rs
  automerge-backend/tests/get_patch.rs
  automerge-c/src/lib.rs
  automerge-cli/src/change.rs
  automerge-cli/src/export.rs
  automerge-cli/src/import.rs
  automerge-frontend/tests/test_backend_concurrency.rs
  automerge-frontend/tests/test_cursor.rs
  automerge/benches/crdt_benchmarks.rs
  automerge/benches/save_load.rs
  automerge/benches/sync.rs
  automerge/tests/save_load.rs
  automerge/tests/text_grapheme_clusters.rs
Labels: enhancement

#134 Use elem id from insertion in frontend
  automerge-frontend/src/state_tree/diffable_sequence.rs
  automerge-frontend/src/state_tree/mod.rs
  automerge-frontend/src/state_tree/resolved_path.rs
  automerge/tests/frontend_backend_roundtrip.rs
Labels: bug

#138 Fix expansion of multi insert indexes
  automerge-frontend/src/state_tree/diffable_sequence.rs
  automerge/Cargo.toml
  automerge/tests/frontend_backend_roundtrip.rs
Labels: bug

#140 Add mismatched sequence number failing test
  automerge-frontend/src/lib.rs
  automerge-frontend/src/state_tree/diffable_sequence.rs
  automerge-frontend/src/state_tree/mod.rs
  automerge-frontend/src/state_tree/multivalue.rs
  automerge/tests/frontend_backend_roundtrip.rs
Labels: bug

#120 Refactor travis to have more jobs
  .travis.yml
Labels: enhancement

#144 Make encoding and decoding mods public for errors
  automerge-backend/src/decoding.rs
  automerge-backend/src/encoding.rs
  automerge-backend/src/lib.rs
Labels: bug

#88 Implement new sequence patch format
  automerge-backend-wasm/scripts/js_tests.sh
  automerge-backend-wasm/src/lib.rs
  automerge-backend/Cargo.toml
  automerge-backend/src/actor_map.rs
  automerge-backend/src/backend.rs
  automerge-backend/src/change.rs
  automerge-backend/src/columnar.rs
  automerge-backend/src/concurrent_operations.rs
  automerge-backend/src/expanded_op.rs
  automerge-backend/src/internal.rs
  automerge-backend/src/lib.rs
  automerge-backend/src/object_store.rs
  automerge-backend/src/op_handle.rs
  automerge-backend/src/op_set.rs
  automerge-backend/src/patches.rs
  automerge-backend/src/patches/edits.rs
  automerge-backend/src/patches/from_scratch_diff.rs
  automerge-backend/src/patches/gen_value_diff.rs
  automerge-backend/src/patches/incremental_diff.rs
  automerge-backend/src/patches/patch_workshop.rs
  automerge-backend/src/pending_diff.rs
  automerge-backend/tests/apply_change.rs
  automerge-backend/tests/apply_local_change.rs
  automerge-backend/tests/get_patch.rs
  automerge-frontend/benches/statetree_apply_diff.rs
  automerge-frontend/src/error.rs
  automerge-frontend/src/lib.rs
  automerge-frontend/src/mutation.rs
  automerge-frontend/src/state_tree/diff_application_result.rs
  automerge-frontend/src/state_tree/diffable_sequence.rs
  automerge-frontend/src/state_tree/mod.rs
  automerge-frontend/src/state_tree/multivalue.rs
  automerge-frontend/src/state_tree/resolved_path.rs
  automerge-frontend/src/state_tree/state_tree_change.rs
  automerge-frontend/tests/test_apply_patch.rs
  automerge-frontend/tests/test_backend_concurrency.rs
  automerge-frontend/tests/test_cursor.rs
  automerge-frontend/tests/test_frontend.rs
  automerge-frontend/tests/test_mutation.rs
  automerge-protocol/src/lib.rs
  automerge-protocol/src/serde_impls/diff.rs
  automerge-protocol/src/serde_impls/mod.rs
  automerge-protocol/src/serde_impls/op.rs
  automerge-protocol/src/serde_impls/op_type.rs
  automerge-protocol/src/serde_impls/root_diff.rs
  automerge-protocol/tests/serde_round_trip_proptest.rs
  automerge/Cargo.toml
  automerge/tests/frontend_backend_roundtrip.rs
Labels: enhancement

#131 Set console_error_panic_hook when initing a backend
  automerge-backend-wasm/src/lib.rs
Labels: enhancement

#148 Remove unused variables in diffable sequence
  automerge-frontend/src/state_tree/diffable_sequence.rs
Labels: performance
